// This file is generated by omniidl (C++ backend)- omniORB_4_0. Do not edit.

#include "bootstrap.hh"
#include <omniORB4/callDescriptor.h>

static const char* _0RL_library_version = omniORB_4_0;

CORBA_InitialReferences_ptr CORBA_InitialReferences_Helper::_nil() {
  return CORBA_InitialReferences::_nil();
}

CORBA::Boolean CORBA_InitialReferences_Helper::is_nil(CORBA_InitialReferences_ptr p) {
  return CORBA::is_nil(p);

}

void CORBA_InitialReferences_Helper::release(CORBA_InitialReferences_ptr p) {
  CORBA::release(p);
}

void CORBA_InitialReferences_Helper::duplicate(CORBA_InitialReferences_ptr p) {
  if( p && !p->_NP_is_nil() )  omni::duplicateObjRef(p);
}

void CORBA_InitialReferences_Helper::marshalObjRef(CORBA_InitialReferences_ptr obj, cdrStream& s) {
  CORBA_InitialReferences::_marshalObjRef(obj, s);
}

CORBA_InitialReferences_ptr CORBA_InitialReferences_Helper::unmarshalObjRef(cdrStream& s) {
  return CORBA_InitialReferences::_unmarshalObjRef(s);
}

CORBA_InitialReferences_ptr
CORBA_InitialReferences::_duplicate(CORBA_InitialReferences_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);

  return obj;
}

CORBA_InitialReferences_ptr
CORBA_InitialReferences::_narrow(CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}

CORBA_InitialReferences_ptr
CORBA_InitialReferences::_nil()
{
  static _objref_CORBA_InitialReferences* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
  if( !_the_nil_ptr )  _the_nil_ptr = new _objref_CORBA_InitialReferences;
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
}

const char* CORBA_InitialReferences::_PD_repoId = "omg.org/CORBA/InitialReferences:1.0";

_objref_CORBA_InitialReferences::~_objref_CORBA_InitialReferences() {}

_objref_CORBA_InitialReferences::_objref_CORBA_InitialReferences(omniIOR* ior, omniIdentity* id, omniLocalIdentity* lid) :
   
   omniObjRef(CORBA_InitialReferences::_PD_repoId, ior, id, lid)
{
  _PR_setobj(this);
}

void*
_objref_CORBA_InitialReferences::_ptrToObjRef(const char* id)
{
  if( !strcmp(id, CORBA::Object::_PD_repoId) )
    return (CORBA::Object_ptr) this;
  if( !strcmp(id, CORBA_InitialReferences::_PD_repoId) )
    return (CORBA_InitialReferences_ptr) this;
  
  return 0;
}

// Local call call-back function.
static void
_0RL_lcfn_96f078e2247ab9da_00000000(omniCallDescriptor* cd, omniServant* svnt)
{
  omniStdCallDesc::_cCORBA_mObject_i_cstring* tcd = (omniStdCallDesc::_cCORBA_mObject_i_cstring*) cd;
  _impl_CORBA_InitialReferences* impl = (_impl_CORBA_InitialReferences*) svnt->_ptrToInterface(CORBA_InitialReferences::_PD_repoId);
  tcd->pd_result = impl->get(tcd->arg_0);
}

CORBA::Object_ptr _objref_CORBA_InitialReferences::get(const char* id)
{
  omniStdCallDesc::_cCORBA_mObject_i_cstring _call_desc(_0RL_lcfn_96f078e2247ab9da_00000000, "get", 4, id);
  
  _invoke(_call_desc);
  return _call_desc.result();
}

// Proxy call descriptor class. Mangled signature:
//  _cCORBA__InitialReferences_mObjIdList
class _0RL_cd_96f078e2247ab9da_10000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_96f078e2247ab9da_10000000(LocalCallFn lcfn, const char* op, size_t oplen, _CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op, oplen, 0, 0, 0, upcall) {}

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
    
  inline CORBA_InitialReferences::ObjIdList* result() { return pd_result._retn(); }
  
  CORBA_InitialReferences::ObjIdList_var pd_result;
};

void _0RL_cd_96f078e2247ab9da_10000000::unmarshalReturnedValues(cdrStream& s)
{
  
  pd_result = new CORBA_InitialReferences::ObjIdList;
  
  (CORBA_InitialReferences::ObjIdList&)pd_result <<= s;
  
}

void _0RL_cd_96f078e2247ab9da_10000000::marshalReturnedValues(cdrStream& s)
{
    (CORBA_InitialReferences::ObjIdList&)pd_result <<= s;
}

// Local call call-back function.
static void
_0RL_lcfn_96f078e2247ab9da_20000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_96f078e2247ab9da_10000000* tcd = (_0RL_cd_96f078e2247ab9da_10000000*) cd;
  _impl_CORBA_InitialReferences* impl = (_impl_CORBA_InitialReferences*) svnt->_ptrToInterface(CORBA_InitialReferences::_PD_repoId);
  tcd->pd_result = impl->list();
}

CORBA_InitialReferences::ObjIdList* _objref_CORBA_InitialReferences::list()
{
  _0RL_cd_96f078e2247ab9da_10000000 _call_desc(_0RL_lcfn_96f078e2247ab9da_20000000, "list", 5);
  
  _invoke(_call_desc);
  return _call_desc.result();
}

_pof_CORBA_InitialReferences::~_pof_CORBA_InitialReferences() {}

omniObjRef*
_pof_CORBA_InitialReferences::newObjRef(omniIOR* ior,
               omniIdentity* id, omniLocalIdentity* lid)
{
  return new _objref_CORBA_InitialReferences(ior, id, lid);
}

CORBA::Boolean
_pof_CORBA_InitialReferences::is_a(const char* id) const
{
  if( !strcmp(id, CORBA_InitialReferences::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_CORBA_InitialReferences _the_pof_CORBA__InitialReferences;

_impl_CORBA_InitialReferences::~_impl_CORBA_InitialReferences() {}

CORBA::Boolean
_impl_CORBA_InitialReferences::_dispatch(GIOP_S& giop_s)
{
  const char* op = giop_s.invokeInfo().operation();

  if( !strcmp(op, "get") ) {

    omniStdCallDesc::_cCORBA_mObject_i_cstring _call_desc(_0RL_lcfn_96f078e2247ab9da_00000000, "get", 4, 0, 1);
    _upcall(giop_s,_call_desc);
    return 1;
  }

  if( !strcmp(op, "list") ) {
    
    _0RL_cd_96f078e2247ab9da_10000000 _call_desc(_0RL_lcfn_96f078e2247ab9da_20000000, "list", 5, 1);
    _upcall(giop_s,_call_desc);
    return 1;
  }

  return 0;
}

void*
_impl_CORBA_InitialReferences::_ptrToInterface(const char* id)
{
  if( !strcmp(id, CORBA::Object::_PD_repoId) )
    return (void*) 1;
  if( !strcmp(id, CORBA_InitialReferences::_PD_repoId) )
    return (_impl_CORBA_InitialReferences*) this;
  
  return 0;
}

const char*
_impl_CORBA_InitialReferences::_mostDerivedRepoId()
{
  return CORBA_InitialReferences::_PD_repoId;
}

POA_CORBA_InitialReferences::~POA_CORBA_InitialReferences() {}

