.TH catior 1 "8 May 97" "ORL"

.SH NAME
catior \- Utility for viewing components of a stringified IOR

.SH SYNOPSIS
.B catior
[-x]
<stringified IOR>

.SH DESCRIPTION
catior displays the components of the stringified object reference
supplied to it.

.SH OPTIONS
.TP
.B \-x
Display the object key in hexadecimal

.SH SEE ALSO
genior(1)
