# -*- python -*-
#                           Package   : omniidl
# __init__.py               Created on: 1999/11/11
#			    Author    : David Scott (djs)
#
#    Copyright (C) 1999 AT&T Laboratories Cambridge
#
#  This file is part of omniidl.
#
#  omniidl is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
#  02111-1307, USA.
#
# Description:
#
#   Entrypoint to skeleton generation code

# $Id$
# $Log$
# Revision 1.2  1999/11/19 20:10:13  djs
# Now runs the poa generating code after the main code
#
# Revision 1.1  1999/11/12 17:18:57  djs
# Struct skeleton code added
#

# -----------------------------
# Configuration data
from omniidl.be.cxx import config

# -----------------------------
# Utility functions
from omniidl.be.cxx import tyutil, util

from omniidl.be.cxx.skel import main
from omniidl.be.cxx.skel import poa

def monolithic(stream, tree):
    """Creates one large skeleton with all code inside"""
    stream.out("""\
// This file is generated by @Config.program_Name()@- @Config.omniORB_Library_Version()@. Do not edit.

#include "@Config.basename()@@Config.hdrsuffix()@"
#include <omniORB3/callDescriptor.h>

static const char* @Config.name_prefix()@_library_version = @Config.omniORB_Library_Version()@;


""", Config = config)

    skel = main.__init__(stream)
    tree.accept(skel)

    poa_skel = poa.__init__(stream)
    tree.accept(poa_skel)


def run(tree):
    # create somewhere to put the output
    skel_filename = config.basename() + config.skelsuffix()
    stream = util.Stream(open(skel_filename, "w"), 2)
    #stream = util.Stream(sys.stdout, 2)

    # generate one big chunk of code
    monolithic(stream, tree)




