#
# narrow Makefile
#
# @(#) Makefile 1.4@(#)
#

include ../idl_make_vars

NARROW_FILES	= \
		nr_narrow.cc

NARROW_OBJS	= $(NARROW_FILES:.cc=.o)

NARROW_LIB_NAME	= libnarrow.a

all: $(NARROW_LIB_NAME)

$(NARROW_LIB_NAME): $(NARROW_OBJS)
	$(AR) $(ARFLAGS) $@ $(NARROW_OBJS)
	$(RANLIB) $@

clean:
	/bin/rm -f $(NARROW_OBJS) $(NARROW_LIB_NAME) *~
