
Object eg1_exe.o
{
    Executable eg1
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
}

Object eg2_clt_exe.o
{
    Executable eg2_clt
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
}

Object eg2_impl_exe.o
{
    Executable eg2_impl
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
}

Object eg3_clt_exe.o
{
    Executable eg3_clt
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
}

Object eg3_impl_exe.o
{
    Executable eg3_impl
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
}

