
module ValueTest {
  valuetype One {
    public string s;
    public long   l;
  };

  struct Two {
    string s;
    long l;
  };

  interface Test {
    One op1(in One a, in One b);
    Two op2(in Two a);
  };
};
