// some types used for testing

#ifndef _RDITestTypes_IDL_
#define _RDITestTypes_IDL_

#pragma prefix "research.att.com"
#pragma javaPackage "com.att.research"

module RDITestTypes {

  typedef sequence<string> StringSeq;
  typedef sequence<double> DoubleSeq;

};

#endif

