//File: CosEventComm.idl
//Part of the Event Service

#ifndef _COS_EVENT_COMM_IDL_
#define _COS_EVENT_COMM_IDL_

// omniORB specific pragmas to insert extra includes into the stub header.
#pragma hh #ifndef __COS_SYSDEP_H_EXTERNAL_GUARD__
#pragma hh #define __COS_SYSDEP_H_EXTERNAL_GUARD__
#pragma hh #include "COS_sysdep.h"
#pragma hh #endif

#pragma prefix "omg.org"

module CosEventComm {

	exception Disconnected{};

	interface PushConsumer {
		void push (in any data) raises(Disconnected);
		void disconnect_push_consumer(); 
	};

    interface PushSupplier {
		void disconnect_push_supplier();
	};

	interface PullSupplier {
		any pull () raises(Disconnected);
		any try_pull (out boolean has_event) 
			raises(Disconnected);
		void disconnect_pull_supplier(); 
	};

	interface PullConsumer {
		void disconnect_pull_consumer();
	};

};
#endif /* ifndef _COS_EVENT_COMM_IDL_ */
