//File: SecurityLevel1.idl
//Part of the Security Service

#ifndef _SECURITY_LEVEL_1_IDL
#define _SECURITY_LEVEL_1_IDL

// omniORB specific pragmas to insert extra includes into the stub header.
#pragma hh #ifndef __COS_SYSDEP_H_EXTERNAL_GUARD__
#pragma hh #define __COS_SYSDEP_H_EXTERNAL_GUARD__
#pragma hh #include "COS_sysdep.h"
#pragma hh #endif

#include <Security.idl>

#pragma prefix "omg.org"

module SecurityLevel1 {

    interface Current : CORBA::Current {	// Locality Constrained

        // thread specific operations

        Security::AttributeList get_attributes (            
            in    Security::AttributeTypeList  attributes 
        );

    };
};
#endif /* _SECURITY_LEVEL_1_IDL */
