#
# ast Makefile
#
# @(#) Makefile 1.5@(#)
#

include ../idl_make_vars

AST_FILES	= \
		ast_array.cc \
		ast_argument.cc \
		ast_attribute.cc \
		ast_check.cc \
		ast_concrete_type.cc \
		ast_constant.cc \
		ast_decl.cc \
		ast_enum.cc \
		ast_enum_val.cc \
		ast_exception.cc \
		ast_expression.cc \
		ast_field.cc \
		ast_interface.cc \
		ast_interface_fwd.cc \
		ast_module.cc \
		ast_operation.cc \
		ast_predefined_type.cc \
		ast_root.cc \
		ast_sequence.cc \
		ast_string.cc \
		ast_structure.cc \
		ast_type.cc \
		ast_typedef.cc \
		ast_union.cc \
		ast_union_branch.cc \
		ast_union_label.cc \
		ast_generator.cc \
		ast_redef.cc \
		ast_recursive.cc

AST_OBJS	= $(AST_FILES:.cc=.o)

AST_LIB_NAME	= libast.a

all: $(AST_LIB_NAME)

$(AST_LIB_NAME): $(AST_OBJS)
	$(AR) $(ARFLAGS) $@ $(AST_OBJS)
	$(RANLIB) $@

clean:
	/bin/rm -f $(AST_OBJS) $(AST_LIB_NAME) *~
