// echolag.idl -- like the echo example, but is always one string behind

interface omniLifeCycleInfo;

interface EchoLagFactory;

interface EchoLag {
  string echoStringLag(in string str);
  void   move(in EchoLagFactory there);
  void   remove();
};

interface EchoLagFactory {
  EchoLag new_EchoLag();
  EchoLag copy_EchoLag(in string str, in omniLifeCycleInfo li);
};
