Object diner_a.o
{
    Executable diner
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
    ULibrary llibc.o
}

Object prodcons_a.o
{
    Executable prodcons
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
    ULibrary llibc.o
}

Object thrspecdata_a.o
{
    Executable thrspecdata
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
    ULibrary llibc.o
}

Object prio_a.o
{
    Executable prio
    ULibrary libpthreads.o
    ULibrary plibc.o
    ULibrary llibc++.o
    ULibrary llibc.o
}
