# -*- python -*-
#                           Package   : omniidl
# main.py                   Created on: 2000/08
#			    Author    : David Scott (djs)
#
#    Copyright (C) 2000 AT&T Laboratories Cambridge
#
#  This file is part of omniidl.
#
#  omniidl is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
#  02111-1307, USA.
#
# Description:
#
#   Hook new AMI code into the existing compiler routines
#
# $Id$
# $Log$
# Revision 1.1.2.2  2000/09/28 18:29:21  djs
# Bugfixes in Poller (wrt timout behaviour and is_ready function)
# Removed traces of Private POA/ internal ReplyHandler servant for Poller
# strategy
# Fixed nameclash problem in Call Descriptor, Poller etc
# Uses reference counting internally rather than calling delete()
# General comment tidying
#

from omniidl_be.cxx.ami import hooks, ami

import main
self = main

# AMI code is generated by hooking into the normal backend code and
# adding new definitions.
def __init_hooks__():
    # Hook into existing IDL compiler code
    import omniidl_be.cxx.header.defs
    hooks.defs_visitInterface = omniidl_be.cxx.header.defs.visitInterface
    omniidl_be.cxx.header.defs.visitInterface = hooks.Interface_defs

    import omniidl_be.cxx.header.opers
    hooks.opers_visitInterface = omniidl_be.cxx.header.opers.visitInterface
    omniidl_be.cxx.header.opers.visitInterface = hooks.Interface_opers

    hooks.poa_visitInterface = omniidl_be.cxx.header.poa.visitInterface
    omniidl_be.cxx.header.poa.visitInterface = hooks.Interface_poa

    import omniidl_be.cxx.skel.main
    hooks.skel_visitInterface = omniidl_be.cxx.skel.main.visitInterface
    omniidl_be.cxx.skel.main.visitInterface = hooks.Implementation

    import omniidl_be.cxx.skel.poa
    hooks.skel_poa_visitInterface = omniidl_be.cxx.skel.poa.visitInterface
    omniidl_be.cxx.skel.poa.visitInterface = hooks.Implementation_poa



    

    

