#
# ast Makefile
#
# @(#) Makefile 1.3@(#)
#

include	../idl_make_vars

UTIL_FILES	= \
		utl_scope.cc \
		utl_stack.cc \
		utl_string.cc \
		utl_decllist.cc \
		utl_labellist.cc \
		utl_namelist.cc \
		utl_exceptlist.cc \
		utl_strlist.cc \
		utl_list.cc \
		utl_exprlist.cc \
		utl_error.cc \
		utl_indenter.cc \
		utl_identifier.cc \
		utl_idlist.cc \
		utl_global.cc

UTIL_OBJS	= $(UTIL_FILES:.cc=.o)

UTIL_LIB_NAME	= libutil.a

all: $(UTIL_LIB_NAME)

$(UTIL_LIB_NAME): $(UTIL_OBJS)
	$(AR) $(ARFLAGS) $@ $(UTIL_OBJS)
	$(RANLIB) $@

clean:
	/bin/rm -f $(UTIL_OBJS) $(UTIL_LIB_NAME) *~
