#ifndef __ANYEXAMPLE_IDL__
#define __ANYEXAMPLE_IDL__

// Note that when compiling this IDL with omniidl, the -Wba
// command-line flag should be specified.

struct testStruct {
  long l;
  short s;
};

interface anyExample {
  any testOp(in any mesg);
};

#endif // __ANYEXAMPLE_IDL__
