// corbaidl.idl
//
// This file contains the subset of the interface repository
// definitions that is required to build the ORB.


#pragma prefix "omg.org"

//////////////////////////////////////////////////////////////////////
module CORBA {
//////////////////////////////////////////////////////////////////////

  interface IDLType;

  typedef string Identifier;
  typedef string RepositoryId;
  typedef string VersionSpec;


  struct StructMember {
    Identifier name;
    TypeCode type;
    IDLType type_def;
  };
  typedef sequence<StructMember> StructMemberSeq;


  struct UnionMember {
    Identifier name;
    any label;
    TypeCode type;
    IDLType type_def;
  };
  typedef sequence<UnionMember> UnionMemberSeq;


  typedef sequence<Identifier> EnumMemberSeq;


  typedef short Visibility;
  const Visibility PRIVATE_MEMBER = 0;
  const Visibility PUBLIC_MEMBER  = 1;

  struct ValueMember {
    Identifier name;
    RepositoryId id;
    RepositoryId defined_in;
    VersionSpec version;
    TypeCode type;
    IDLType type_def;
    Visibility access;
  };

  typedef sequence <ValueMember> ValueMemberSeq;


  // Sequences of basic types
  typedef sequence<short>              ShortSeq;
  typedef sequence<long>               LongSeq;
  typedef sequence<unsigned short>     UShortSeq;
  typedef sequence<unsigned long>      ULongSeq;
  typedef sequence<float>              FloatSeq;
  typedef sequence<double>             DoubleSeq;
  typedef sequence<boolean>            BooleanSeq;
  typedef sequence<char>               CharSeq;
  typedef sequence<octet>              OctetSeq;
#ifdef HAS_LongLong
  typedef sequence<long long>          LongLongSeq;
  typedef sequence<unsigned long long> ULongLongSeq;
#endif
#ifdef HAS_LongDouble
  typedef sequence<long double>        LongDoubleSeq;
#endif
  typedef sequence<wchar>              WCharSeq;


//////////////////////////////////////////////////////////////////////
};
//////////////////////////////////////////////////////////////////////
