
#pragma prefix "omg.org"


//////////////////////////////////////////////////////////////////////
module CORBA {
//////////////////////////////////////////////////////////////////////


interface IDLType;
typedef string Identifier;


struct StructMember {
  Identifier name;
  TypeCode type;
  IDLType type_def;
};
typedef sequence<StructMember> StructMemberSeq;


struct UnionMember {
  Identifier name;
  any label;
  TypeCode type;
  IDLType type_def;
};
typedef sequence<UnionMember> UnionMemberSeq;


typedef sequence<Identifier> EnumMemberSeq;


//////////////////////////////////////////////////////////////////////
};
//////////////////////////////////////////////////////////////////////
