// Modified form of the OMG Pseudo-IDL from the Messaging spec

// (base valuetype replaced with a struct)

module Messaging{

  interface ReplyHandler {};

  struct ExceptionHolder_base{ /* should be value */
    boolean         pd_is_system_exception;
    boolean         pd_byte_order;
    sequence<octet> pd_marshaled_exception;
  };

};
