// Modified form of the OMG Pseudo-IDL from the Messaging spec
//
// Treat the ExceptionHolder value as if it were a struct. Add methods
// to it by inheritance.
//
// Poller valuetype is created by hand in Messaging.{cc, h}

module Messaging{

  interface ReplyHandler {};

  struct ExceptionHolder_base{ /* should be value */
    boolean         pd_is_system_exception;
    boolean         pd_byte_order;
    sequence<octet> pd_marshaled_exception;
  };

};
