
#pragma prefix "omg.org"

#include <corbaidl.idl>


//////////////////////////////////////////////////////////////////////
module PortableServer {
//////////////////////////////////////////////////////////////////////


  // forward reference
  interface POA;

  typedef sequence<POA> POAList;

  //??native Servant;
  typedef short Servant;

  typedef sequence<octet> ObjectId;


//////////////////////////////////////////////////////////////////////
};
//////////////////////////////////////////////////////////////////////
