
#ifndef _omniorb_poa_include_idl_
#define _omniorb_poa_include_idl_

#pragma prefix "omg.org"

#include <corbaidl.idl>


//////////////////////////////////////////////////////////////////////
module PortableServer {
//////////////////////////////////////////////////////////////////////


  // forward reference
  interface POA;

  typedef sequence<POA> POAList;

  //??native Servant;
  typedef short Servant;

  typedef sequence<octet> ObjectId;


//////////////////////////////////////////////////////////////////////
};
//////////////////////////////////////////////////////////////////////

#endif // _omniorb_poa_include_idl_
