#pragma prefix "omg.org"

//////////////////////////////////////////////////////////////////////
module CORBA {
//////////////////////////////////////////////////////////////////////


  // From the CORBA Messaging spec
  interface PollableSet;
  
  interface Pollable{
    boolean is_ready(in unsigned long timeout);
    PollableSet create_pollable_set();
  };
  
  interface DIIPollable: Pollable{};
  
  interface PollableSet{
    exception NoPossiblePollable {};
    exception UnknownPollable {};
    
    typedef sequence<Pollable> set_T;
    
    DIIPollable create_dii_pollable();
    
    void add_pollable(in Pollable potential);
    
    Pollable poll(in unsigned long timeout) raises( NoPossiblePollable );
    
    void remove(in Pollable potential) raises( UnknownPollable );
    
    unsigned short number_left();
  };


//////////////////////////////////////////////////////////////////////
};
//////////////////////////////////////////////////////////////////////
