
// We need a separate version of this IDL file with a different
// name, merely to ensure that the stubs are re-compiled with the
// the right options.


#ifndef __ECHO_IDL__
#define __ECHO_IDL__

interface Echo {
  string echoString(in string mesg);
};

#endif 
