.TH convertior 1 "8 May 97" "ORL"

.SH NAME
convertior \- Utility for creating a new IOR from existing.
changing the hostname of an existing stringified IOR

.SH SYNOPSIS
.B convertior
[\-x]
<stringified IOR> <New Hostname>

.SH DESCRIPTION
convertior accepts a stringified IOR and a new hostname, then outputs
a new IOR for the combination.

.SH OPTIONS
.TP
None


.SH SEE ALSO
genior(1) catior(1)
