.TH ols 1 "22.10.96" "ORL"
.SH NAME
ols \- list source files in an OMNI build tree
.SH SYNOPSIS
.B ols
.I [file]
.SH DESCRIPTION
This command is only of any use inside an OMNI build tree.  When given no
arguments it finds the directory corresponding to the current directory in each
of the source trees and lists all the files there.

When given an argument it searches for that file in the current directory and
the corresponding directory in each of the source trees.  If it finds the file
then it prints the full path.  This can be usefully used in backticks to
operate on the source file, whichever source tree it happens to be in, e.g.
.B more `ols foo.cc`
 
.SH SEE ALSO
.BR obuildtree (1)
.BR omake (1)

.SH FILES
.TP 5
.B <top>/config/sources
contains a list of the source trees if this is an OMNI build tree.

.SH AUTHOR
Tristan Richardson, ORL
