#
# driver Makefile
#
# @(#) Makefile 1.4@(#)
#

include ../idl_make_vars

DRIVER_LIB = \
		drv_init.cc \
		drv_private.cc \
		drv_main.cc \
		drv_args.cc \
		drv_fork.cc \
		drv_link.cc \
		drv_preproc.cc

DRIVER_LIB_NAME=libdrv.a

DRIVER_OBJ = $(DRIVER_LIB:.cc=.o)

all: $(DRIVER_LIB_NAME)

$(DRIVER_LIB_NAME): $(DRIVER_OBJ)
	$(AR) $(ARFLAGS) $@ $(DRIVER_OBJ)
	$(RANLIB) $@

clean:
	/bin/rm -f $(DRIVER_OBJ) $(DRIVER_LIB_NAME) *~
